# Main Deno Container
FROM quay.io/chapeaux/deno:1.25.0 as deno

# Testing container
FROM registry.redhat.io/ubi9/nodejs-16 as builder

USER 0
ADD ./docker/etc /etc
RUN update-crypto-policies --set LEGACY && \
  yum install -y xdg-utils liberation-fonts google-chrome-stable && \
  update-crypto-policies --set DEFAULT && \
  yum clean all

WORKDIR /usr/src/app

COPY --chown=1001:0 ["package*.json", "./"]
COPY --from=deno /usr/local/bin/deno /usr/local/bin/deno

USER 1001

# Install the dependencies
RUN npm ci
ADD . .

EXPOSE 8080/tcp
EXPOSE 8443/tcp

CMD [ "deno", "task", "serve" ]
