container:
  - container/**
  - .dockerignore
  - Containerfile
  - Containerfile.test

github:
  - .github/**

scripts:
  - tasks/**

docs:
  - docs/**
  - '**/*.md'

test:
  - components/**/test/**

# CPX Components Labels
cpx-auth:
  - components/cpx-auth/**
cpx-cookie:
  - components/cpx-cookie/**
cpx-filter:
  - components/cpx-filter/**
cpx-keycloak:
  - components/cpx-keycloak/**
cpx-newsdesk:
  - components/cpx-newsdesk/**
cpx-operator-graph:
  - components/cpx-operator-graph/**
cpx-query:
  - components/cpx-query/**
cpx-reporter:
  - components/cpx-reporter/**
cpx-result:
  - components/cpx-result/**
cpx-search:
  - components/cpx-search/**
cpx-state:
  - components/cpx-state/**
cpx-tab-stream:
  - components/cpx-tab-stream/**
cpx-target:
  - components/cpx-target/**
cpx-url:
  - components/cpx-url/**
cpx-user:
  - components/cpx-user/**
cpx-websocket:
  - components/cpx-websocket/**
